config/routes.rb
Cpt::Application.routes.draw do
  resources :word_audio_status, only: [:index, :show, :update, :edit]
  resources :glue_words, only: [:new]
  post 'glue_words/upload', to: 'glue_words#upload', as: 'glue_words_upload'

  resources :content_packs
  resources :pronunciations, only: [:index, :update]
  resources :audios, only: [:update]

  resources :content_packs do
    resources :topics, shallow: true
    resources :selections

    post 'topics/ordering/:id', to: 'topics#ordering', as: 'ordering_topics'
    post 'selections/ordering/:id', to: 'selections#ordering', as: 'ordering_selections'
    get 'selections/:id/move_copy', to: 'selections#move_copy', as: 'move_copy_new'
    post 'selections/:id/move', to: 'selections#move'
    post 'selections/:id/copy', to: 'selections#copy'
  end

  get 'auth/:provider', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#index', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => "content_packs#index"

end

app/models/content_pack.rb
class ContentPack < ActiveRecord::Base
  validates :user_id, :presence => true
  validates :content_type_id, :presence => true
  validates :status_id, :presence => true
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 256}
  validates :description, :length => {:maximum => 1024}
  
  # Notice: before_* filters must before associations 
  before_validation :set_association_value
  before_create :create_default_topic
  before_destroy :ensure_content_pack_is_empty
  # after_destroy :destroy_associated_topics
  
  belongs_to :status
  belongs_to :content_type
  belongs_to :user
  has_many :topics, dependent: :destroy
  
  default_scope {order("updated_at desc")}
  
  STATUS_PUBLISHED = "Published"
  
  def published?
    status.name.eql? STATUS_PUBLISHED
  end
  
  def empty?
    topics.reduce(true) {|empty, t| empty &&= t.empty?}
  end

  def max_priority
    topics.maximum :priority
  end
  
  def create_default_topic
    topics.build name: Topic.generate_def_name, grade_level: 1, default: true, priority: 0
  end
  
  def default_topic
    topics.find_by_default true
  end
  
  private
    def set_association_value
      self.status ||= Status.first
      self.content_type ||= ContentType.first
    end
    
    def ensure_content_pack_is_empty
      unless empty?
        errors.add(:error, I18n.t('content_packs.controller.delete.failed', name: self.name))
        false
      end
    end

    def destroy_associated_topics
      topics.destroy_all
    end
end

app/controllers/content_packs_controller.rb
class ContentPacksController < ApplicationController
  before_action :set_content_pack, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /content_packs
  # GET /content_packs.json
  def index
    @content_packs = ContentPack.all
  end

  # GET /content_packs/1
  # GET /content_packs/1.json
  def show
  end

  # GET /content_packs/new
  def new
    @content_pack = ContentPack.new
    @content_types = ContentType.all
    render :layout => false
  end

  # GET /content_packs/1/edit
  def edit
    if @content_pack.empty?
      @content_types = ContentType.all
    end
    render :layout => false
  end

  # POST /content_packs
  # POST /content_packs.json
  def create
    @content_pack = ContentPack.new(content_pack_params)
    @content_pack.user = current_user
    respond_to do |format|
      if @content_pack.save
        @content_packs = ContentPack.all
      else
        @content_types = ContentType.all
      end
      format.js
    end
  end

  # PATCH/PUT /content_packs/1
  # PATCH/PUT /content_packs/1.json
  def update
    respond_to do |format|
      if !@content_pack.published? && @content_pack.update(content_pack_params)
        @content_packs = ContentPack.all
      elsif @content_pack.empty?
        @content_types = ContentType.all
      end
      format.js
    end
  end

  # DELETE /content_packs/1
  # DELETE /content_packs/1.json
  def destroy
    if @content_pack.destroy
      render json: {success: true}
    else
      render json: @content_pack.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_pack
      @content_pack = ContentPack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_pack_params
      params.require(:content_pack).permit(:name, :description, :content_type_id)
    end

end

app/helpers/content_packs_helper.rb
module ContentPacksHelper
  def error_notification(content_pack, action)
    type = content_pack.published? ? 'published' : 'not_empty'
    I18n.t "content_packs.controller.#{action}.failed.#{type}", name: content_pack.name
  end
end

app/views/content_packs/_form.html.erb
<%= form_for @content_pack, remote: true, html: { class: "pure-form dialog-content-form" } do |f| %>
  <%= error_explanation @content_pack %>
  <div class="pure-control-group">
    <%= f.label :name, :id => "content_pack_name_label" do%>
      Name<attr title="required">*</attr>
    <% end %>
    <%= f.text_field :name, :placeholder => "content name", :class => "pure-input-2-3", :maxlength => 256 %>
  </div>
  <div class="pure-control-group">
    <%= f.label :content_type_id do%>
      Type<attr title="required">*</attr>
    <% end %>
    <% if @content_types.nil? %>
      <span class="content-pack-type"><%= @content_pack.content_type.name %></span>
    <% else %>
      <%= f.select :content_type_id, options_from_collection_for_select(@content_types, "id", "name", @content_pack.content_type_id), :class => "pure-input-medium", :required => true %>
    <% end %>
  </div>
  <div class="pure-control-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :maxlength => 1024, :placeholder => "description", :class => "pure-input-1", :rows => 10 %>
  </div>
  <div class="pure-u-1">
    <attr>*</attr>Indicates required field.
  </div>
  <div class="actions">
    <%= f.button "Save", class: "pure-button pure-button-small pure-button-success", data: { disable_with: "Please wait..." } %>
    <%= f.button "Cancel", type: "button", class: "pure-button pure-button-small pure-button-cancel", data: { dismiss: true } %>
  </div>
<% end %>

app/views/content_packs/_table.erb
<table class="pure-table pure-table-horizontal pure-table-striped pure-table-1" id="content_packs_table">
  <colgroup>
    <col style="width: 210px;">
    <col style="width: 263px;">
    <col style="width: 152px;">
    <col style="width: 125px;">
    <col style="width: 90px;">
    <col style="width: 116px;">
  </colgroup>
  <thead>
    <tr>
      <th>
        <div unselectable="on" class="sort-liner">
          Name<i class="sort-indicator"></i>
        </div>
      </th>
      <th>
        Description
      </th>
      <th>
        <div class="sort-liner" unselectable="on">
          Last Edited Date<i class="sort-indicator"></i>
        </div>
      </th>
      <th>
        <div unselectable="on" class="sort-liner">
          Type<i class="sort-indicator"></i>
        </div>
      </th>
      <th>
        <div unselectable="on" class="sort-liner">
          Status<i class="sort-indicator"></i>
        </div>
      </th>
      <th>
        <div unselectable="on" class="sort-liner">
          Created By<i class="sort-indicator"></i>
        </div>
      </th>
      <th class="hide"></th>
    </tr>
  </thead>
  <tbody>
    <% @content_packs.each do |content_pack| %>
    <tr>
      <td>
        <%= link_to "", content_pack_path(content_pack.id), :title => "Delete", :class => "icon-delete#{' disabled' unless content_pack.empty?}", :data => {:name => content_pack.name, :message => error_notification(content_pack, "delete")}, "delete-for" => content_pack.name %>
        <%= link_to "", edit_content_pack_path(content_pack),:title => "Edit Setting",:data => { :message => error_notification(content_pack, "edit")}, :class => "icon-edit#{' disabled' if content_pack.published?}", "edit-for" => content_pack.name %>
        <%= link_to content_pack.name, content_pack_topics_path(content_pack.id), :class => "content-pack-name", :title => content_pack.name %>
      </td>
      <td class="content-pack-description"><%= content_pack.description %></td>
      <td class="content-pack-last-update-date"><%= l(content_pack.updated_at, format: :m_d_y ) %></td>
      <td class="content-pack-type"><%= content_pack.content_type.name %></td>
      <td class="content-pack-status"><%= content_pack.status.name %></td>
      <td class="content-pack-created-by"><%= content_pack.user.name %></td>
      <td class="hide"><%= content_pack.updated_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/content_packs/create.js.erb
var data = "<%= escape_javascript(render(@content_pack.errors.any? ? 'form' : 'table')) %>";
if(<%= @content_pack.errors.any? %>) {
	$('#new_content_packs_dialog .aui_content').html(data);
} else {
	var container = $('#content_packs_table');
	container.dataTable().fnDestroy();
	scilearn.panel["newContentPack"].close();
	container.html(data);
	scilearn.pack.initTable()
}

app/views/content_packs/edit.html.erb
<%= render 'form' %>

app/views/content_packs/index.html.erb
<section class="content-container pure-u-1">
  <div class="content">
    <header class="pure-u-1">
      <h1>
        Content Packs
      </h1>
      <div class="button-group">
        <%= link_to "New Content Pack", new_content_pack_path, :class => "pure-button pure-button-info pure-button-small", :id => "new_content_pack_link" %>
        <%= link_to "Manage Audio Library", "#", :class => "pure-button pure-button-small", :disabled => true %>
      </div>
    </header>
    <div class="pure-u-1">
      <%= render 'table' %>
    </div>
  </div>
</section>

app/views/content_packs/new.html.erb
<%= render 'form' %>

app/views/content_packs/update.js.erb
if(<%= @content_pack.published? %>) {
	scilearn.notification.error("<%= I18n.t('content_packs.controller.update.failed', name: @content_pack.name) %>");
} else {
	var data = "<%= escape_javascript(render(@content_pack.errors.any? ? 'form' : 'table')) %>";
	if(<%= @content_pack.errors.any? %>) {
		$('#edit_content_packs_dialog .aui_content').html(data);
	} else {
		var container = $("#content_packs_table");
		if(container.length === 1) {
			container.dataTable().fnDestroy();
			container.html(data);
			scilearn.pack.initTable()
		} else {
			 $(".content header .content-title").text("<%= @content_pack.name %>");
		}
		scilearn.panel["editContentPack"].close();
	}
}