config/routes.rb
Cpt::Application.routes.draw do
  resources :word_audio_status, only: [:index, :show, :update, :edit]
  resources :glue_words, only: [:new]
  post 'glue_words/upload', to: 'glue_words#upload', as: 'glue_words_upload'

  resources :content_packs
  resources :pronunciations, only: [:index, :update]
  resources :audios, only: [:update]

  resources :content_packs do
    resources :topics, shallow: true
    resources :selections

    post 'topics/ordering/:id', to: 'topics#ordering', as: 'ordering_topics'
    post 'selections/ordering/:id', to: 'selections#ordering', as: 'ordering_selections'
    get 'selections/:id/move_copy', to: 'selections#move_copy', as: 'move_copy_new'
    post 'selections/:id/move', to: 'selections#move'
    post 'selections/:id/copy', to: 'selections#copy'
  end

  get 'auth/:provider', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#index', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => "content_packs#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content_pack_id, :presence =>true
  validates :name, :presence => true, uniqueness: { scope: :content_pack_id }, :length => {:maximum => 256}
  validates :grade_level, :format => { :with => /\A\d+??(?:\.\d{0,2})?\z/}, :presence => true, :numericality => { less_than: 101, greater_than_or_equal_to: 1}
  validates :default, :inclusion => {:in => [true, false]}

  before_validation :set_init_value
  before_save :ensure_content_pack_is_not_published
  before_create :move_selections_to_first_topic
  before_destroy :ensure_content_pack_is_not_published
  before_destroy :ensure_topic_is_empty
  
  has_many :selections
  belongs_to :content_pack
  
  default_scope {order("topics.default DESC, priority DESC")}
  
  def self.generate_def_name
    def_name = "default_topic_";
    50.times{ def_name << ((rand(2)==1?65:97) + rand(25)).chr }
    def_name
  end
  
  def max_priority
    selections.maximum(:priority) || -1
  end
  
  def empty?
    selections.empty?
  end
  
  def total_selections
    selections.size
  end
  
  # Move current topic to specified location, and other topics' location within the same
  # content pack will be updated automatically by sequence
  #
  # User orders topics through drag/drop Topic rows, we use <tt>priority</tt> in database
  # to indicate their orders within ContentPack
  #
  # * *Args*   :
  #   - +to_priority+ - the location current topic will be moved to
  # * *Rails*   :
  #   - ActiveRecord::Rollback
  #
  def ordering(to_priority)
    Topic.transaction do
      if self.priority < to_priority
        content_pack.topics.where("priority <= ? and priority > ?", to_priority, self.priority).each {
          |topic| topic.update_attributes!(:priority => topic.priority - 1)
        }
      else
        content_pack.topics.where("priority >= ? and priority < ?", to_priority, self.priority).each {
          |topic| topic.update_attributes!(:priority => topic.priority + 1)
        }
      end
      self.update_attributes!(priority: to_priority)
    end
  end
  
  private
    def set_init_value
      self.default ||= false
      self.priority ||= content_pack.nil? ? 1 : content_pack.max_priority + 1
    end

    def move_selections_to_first_topic
      if content_pack.topics.count == 1
        default_topic = content_pack.default_topic
        self.selections = default_topic.selections
      end
    end

    def ensure_topic_is_empty
      unless empty?
        errors.add(:error, I18n.t('topics.controller.delete.failed', name: self.name))
        false
      end
    end

    def ensure_content_pack_is_not_published
      if content_pack && content_pack.published?
        errors.add :error, I18n.t('content_packs.controller.update.failed', name: content_pack.name)
        false
      end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy, :ordering]
  before_action :authorize

  # GET /topics/id
  # GET /topics.json
  def index
    @content_pack = ContentPack.find(params[:content_pack_id])
    @topics = @content_pack.topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new/1
  # params[:id] is content pack id
  def new
    @topic = Topic.new
    @topic.content_pack_id = params[:content_pack_id]
    @content_pack = ContentPack.find(params[:content_pack_id])
    render :layout => false
  end

  # GET /topics/1/edit
  def edit
    render :layout => false
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @content_pack = ContentPack.find(params[:content_pack_id])
    respond_to do |format|
      if @topic.save
        @topics = @content_pack.topics
      end
      format.js
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        @content_pack = @topic.content_pack
        @topics = @content_pack.topics
      end
      format.js
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    if @topic.destroy
      render json: {success: true}
    else
      render json: @topic.errors, status: :unprocessable_entity
    end
  end

  # POST /topics/1
  # POST /topics/1.json
  def ordering
    @topic.ordering(params[:to_priority].to_i)
    render nothing:true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :grade_level, :content_pack_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_error_notification(topic, action)
    type = topic.content_pack.published? ? 'published' : 'not_empty'
    I18n.t "topics.controller.#{action}.failed.#{type}", name: topic.name
  end

  # empty when content pack only has default topic and no selection
  def empty? (topics)
    (topics.size == 1 && topics[0].selections.size == 0) || @topics.size == 0
  end
end

app/views/topics/_filter.html.erb
<div id="filter" <%= 'class=hide' if empty?(@topics) %> >
	<%= label_tag(:q, "Filter Selections By") %>
	<%= select_tag :filter_by, options_for_select([['None Selected', 0], ['Status', 1], ['Errors', 2]], 0)%>
	<%= select_tag :filter_status, options_for_select(Status.all.map { |s| [s.name, s.id] }), :class => "hide" %>
	<%= select_tag :filter_errors, options_for_select([['Has Errors', 0], ['No Errors', 1], ['Needs Errors Check']]), :class => "hide" %>
	<%= link_to "Clear filter","#", :class => "link hide", :id => "filter_clear" %>
</div>

app/views/topics/_form.html.erb
<%= form_for [@content_pack, @topic], remote: true, html: { class: "pure-form pure-g dialog-content-form", id: "topic_dialog_form" } do |f| %>
  <%= error_explanation @topic %>
  <%= f.hidden_field :content_pack_id %>
  <div class="pure-control-group">
    <div class="pure-u-1-4">
    <%= f.label :name do %>
      Name <attr title="required">*</attr>
    <% end %>
    </div>
    <div class="pure-u-3-4">
    <%= f.text_field :name, :placeholder => "topic name", :class => "pure-input-1", :maxlength => 256 %>
    </div>
  </div>
  <div class="pure-control-group">
    <div class="pure-u-1-4">
    <%= f.label :grade_level do %>
      Grade Level <attr title="required">*</attr>
    <% end %>
    </div>
    <div class="pure-u-3-4">
    <%= f.number_field :grade_level, :placeholder => "grade level", :class => "pure-input-1", :in => 1..100.99, :step => 0.01 %>
    </div>
  </div>
  <div class="pure-u-1">
    <attr>*</attr>Indicates required field.
  </div>
  <div class="actions pure-u-1">
    <%= f.button "Save", class: "pure-button pure-button-small pure-button-success", data: { disable_with: "Please wait..." } %>
    <%= f.button "Cancel", type: "button", class: "pure-button pure-button-small pure-button-cancel", data: { dismiss: true } %>
  </div>
<% end %>

app/views/topics/_list.html.erb
<ul id="topics_list" class="pure-u-1<%= " empty" if empty?(@topics) %>">
  <li class="topic">
    <ul>
      <li id="topic_header">
        <div class="col col-title">Title</div>
        <div class="col col-grade-level">Grade Level</div>
        <div class="col col-status">Status</div>
        <div class="col col-update-at">Last Edited Date</div>
        <div class="col col-update-by">Last Edited By</div>
        <div class="col col-errors">Errors</div>
      </li>
      <li class="topic-info" id="topic_<%= @topics[0].id %>"  style="display:none">
        <span class="total-count"><%= @topics[0].selections.count %></span>
      </li>
      <% @topics[0].selections.each do |selection| %>
        <li class="selection" id="selection_<%= selection.id %>" status="<%= selection.status.id %>" error="">
          <div class="col col-title">
            <%= link_to "", content_pack_selection_path(@topics[0].content_pack_id, selection.id), :data => {:method => :delete, :name => selection.title}, :class => "icon icon-delete selection-delete", "delete-for" => selection.title, :title => "Delete" %>
            <%= link_to "", edit_content_pack_selection_path(@topics[0].content_pack_id, selection.id), :class => "icon icon-edit selection-edit", "edit-for" => selection.title, :title => "Edit Setting" %>
            <%= link_to "", content_pack_move_copy_new_path(@topics[0].content_pack_id, selection.id), :data => {:method => :get}, :class => "icon icon-copy-move", "move-copy-for" => selection.title, :title => "Move/Copy" %>
            <span title="<%= selection.title %>" class="col-name"><%= selection.title %></span></div>
          <div class="col col-grade-level"></div>
          <div class="col col-status"><%= selection.status.name %></div>
          <div class="col col-update-at"><%= l(selection.updated_at, format: :m_d_y) %></div>
          <div class="col col-update-by"><%= selection.updater.name %></div>
          <div class="col col-errors">-</div>
        </li>
      <% end %>
    </ul>
  </li>
  <% @topics.drop(1).each do |topic| %>
    <li class="topic undefault-topic">
      <ul>
        <li class="topic-info" id="topic_<%=topic.id %>">
          <div class="col col-title">
            <i class="icon icon-drop-down icon-arrow-down"></i>
            <%= link_to "", topic_path(topic.id), :data => {:method => :delete, :name => topic.name, :message => topic_error_notification(topic, "delete")}, :class => "icon icon-delete topic-delete #{'disabled' if !topic.empty?}", "delete-for" => topic.name, :title => "Delete" %>
            <%= link_to "", edit_topic_path(topic.id), :data => {:message => topic_error_notification(topic, "edit")}, :class => "icon icon-edit topic-edit #{'disabled' if topic.content_pack.published?}", "edit-for" => topic.name, :title => "Edit Setting" %>
            <span title="<%= topic.name %>" class="col-name"><%= topic.name %></span>
            (<span class="total-count"><%= topic.selections.count %></span>)
          </div>
          <div class="col col-grade-level"><%= topic.grade_level %></div>
        </li>
        <% topic.selections.each do |selection| %>
          <li class="selection" id="selection_<%= selection.id %>" status="<%= selection.status.id %>" error="">
            <div class="col col-title">
              <%= link_to "", content_pack_selection_path(topic.content_pack_id, selection.id), :data => {:method => :delete, :name => selection.title}, :class => "icon icon-delete selection-delete", "delete-for" => selection.title, :title => "Delete" %>
              <%= link_to "", edit_content_pack_selection_path(topic.content_pack_id, selection.id), :class => "icon icon-edit selection-edit", "edit-for" => selection.title, :title => "Edit Setting" %>
              <%= link_to "", content_pack_move_copy_new_path(topic.content_pack_id, selection.id), :data => {:method => :get}, "move-copy-for" => selection.title, :class => "icon icon-copy-move", :title => "Move/Copy" %>
              <span title="<%= selection.title %>" class="col-name"><%= selection.title %></span></div>
            <div class="col col-grade-level"></div>
            <div class="col col-status"><%= selection.status.name %></div>
            <div class="col col-update-at"><%= l(selection.updated_at, format: :m_d_y) %></div>
            <div class="col col-update-by"><%= selection.updater.name %></div>
            <div class="col col-errors">-</div>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
  <li>
    <% if empty?(@topics) %>
      <p class="empty-info">Content Pack is empty. Create new topics, new selections, or import existing selections.</p>
    <% else %>
      <p class="empty-info">No slections to show with the current filter.</p>
    <% end %>
  </li>
</ul>

app/views/topics/create.js.erb
var data = "<%= escape_javascript(render(@topic.errors.any? ? 'form' : 'list')) %>";
if(<%= @topic.errors.any? %>) {
  scilearn.panel["newTopic"].content(data);
} else {
  scilearn.panel["newTopic"].close();
  $('#topics_list').html($(data).html());
  scilearn.topic.initEvent();
  scilearn.topic.clearFilter();
  <% if @topics and @topics.any? %>
  $('#filter').removeClass('hide');
  $('#topics_list').removeClass('empty');
  <% end %>
}

app/views/topics/edit.html.erb
<%= render 'form' %>

app/views/topics/index.html.erb
<section class="content-container pure-u-1">
  <div class="content">
    <header class="pure-u-1">
      <h1>
        <span class="content-title"><%= @content_pack.name %></span>
        <%= link_to "", edit_content_pack_path(@content_pack), :class => "icon-edit", :title => "Edit Setting" %>
        <%= render "topics/filter" %>
      </h1>
      <h2><strong>Type</strong>: <span><%= @content_pack.content_type.name %></span></h2>
      <%= link_to "< BACK TO CONTENT PACKS", root_path, :class => "link" %>
      <div class="button-group">
        <%= link_to "New Topic", new_content_pack_topic_path(@content_pack, @topic), :class => "pure-button pure-button-info pure-button-small", :id => "new_topic_link" %>
        <%= link_to "New Selection", new_content_pack_selection_path(@content_pack, @topic), :class => "pure-button pure-button-info pure-button-small", :id => "new_selection_link" %>
        <%= link_to "Import Selection", "#", :class => "pure-button pure-button-small", :disabled => true %>
        <div class="pure-button-group">
          <a href="#" class="pure-button">More Actions</a>
          <ul>
            <li><a href="#">Word Audio Dictionary</a></li>
            <li><a href="#">Import Audio</a></li>
          </ul>
        </div>
      </div>
    </header>
    <%= render "topics/list", topics: @topics %>
  </div>
</section>

app/views/topics/new.html.erb
<%= render "form" %>

app/views/topics/update.js.erb
var data = "<%= escape_javascript(render(@topic.errors.any? ? 'form' : 'list')) %>";
if(<%= @topic.errors.any? %>) {
  scilearn.panel["editTopic"].content(data);
} else {
  scilearn.panel["editTopic"].close();
  $('#topics_list').html($(data).html());
  scilearn.topic.initEvent();
  scilearn.topic.clearFilter();
}