config/routes.rb
Cpt::Application.routes.draw do
  resources :word_audio_status, only: [:index, :show, :update, :edit]
  resources :glue_words, only: [:new]
  post 'glue_words/upload', to: 'glue_words#upload', as: 'glue_words_upload'

  resources :content_packs
  resources :pronunciations, only: [:index, :update]
  resources :audios, only: [:update]

  resources :content_packs do
    resources :topics, shallow: true
    resources :selections

    post 'topics/ordering/:id', to: 'topics#ordering', as: 'ordering_topics'
    post 'selections/ordering/:id', to: 'selections#ordering', as: 'ordering_selections'
    get 'selections/:id/move_copy', to: 'selections#move_copy', as: 'move_copy_new'
    post 'selections/:id/move', to: 'selections#move'
    post 'selections/:id/copy', to: 'selections#copy'
  end

  get 'auth/:provider', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#index', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => "content_packs#index"

end

app/models/pronunciation.rb
class Pronunciation < ActiveRecord::Base
  validates :dictionary_key, :presence => true, :length => {:maximum => 255}
  validates :phonemes, :length => {:maximum => 512}
  validates :pronunciation_status_id, :presence => true

  before_validation :ensure_phonemes_format
  before_validation :init_status
  before_save :convert_phonemes

  belongs_to :pronunciation_status
  belongs_to :user

  VALID_PHONEMES = ['AA', 'AE', 'AH', 'AO', 'AW', 'AY', 'B', 'CH', 'D', 'DH', 'EH',
                    'ER', 'EY', 'F', 'G', 'HH', 'IH', 'IY', 'JH', 'K', 'L', 'M', 'N','NG',
                    'OW', 'OY', 'P', 'R', 'S', 'SH', 'T', 'TH', 'UH', 'UW', 'V', 'W', 'Y', 'Z', 'ZH']

  def self.search(search, filter)
    if search || filter
      if search != '' && filter.to_i == 0
        where("dictionary_key like ?", "%#{search}%")
      elsif search == '' && filter.to_i > 0
        where("pronunciation_status_id = ?", "#{filter}")
      elsif search == '' && filter.to_i == 0
        all
      else
        where("dictionary_key like ? and pronunciation_status_id = ?", "%#{search}%", "#{filter}")
      end
    else
      all
    end
  end
  
  private
    def convert_phonemes
      if !self.phonemes.nil? && self.phonemes.index(',')
        Pronunciation.where(dictionary_key: self.dictionary_key).where.not(id: self.id).destroy_all
        arr = self.phonemes.split(',')
        arr[1..-1].each{
          |phoneme| Pronunciation.create(self.attributes.merge(id: nil, phonemes: phoneme))
        }
        self.phonemes = arr[0]
      end
    end
    
    def init_status
      self.pronunciation_status ||= PronunciationStatus.missing
    end
    
    def ensure_phonemes_format
      self.phonemes.gsub(/[,]/,'').split(' ').reduce(true) {|valid, p| valid &&= !VALID_PHONEMES.index(p).nil?} || self.phonemes == '' unless self.phonemes.nil?
    end
end

app/controllers/pronunciations_controller.rb
class PronunciationsController < ApplicationController
  before_action :set_pronunciation, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /pronunciations
  # GET /pronunciations.json
  def index
    if params[:per_page] == nil
      @per_page = 30
    elsif params[:per_page].to_i < 1
      @per_page = Pronunciation.count
    else
      @per_page = params[:per_page].to_i
    end
    @order = params[:order] ? params[:order] : 'asc'
    # @order = params[:order] || 'asc'
    @search = params[:search]
    @filter = params[:filter]
    @pronunciations = Pronunciation
                          .select('pronunciations.*', 'group_concat(phonemes SEPARATOR \', \') as phoneme')
                          .includes(:pronunciation_status)
                          .search(@search, @filter)
                          .order("dictionary_key #@order")
                          .group('dictionary_key')
                          .paginate(page: params[:page], per_page: @per_page)
    @referer_url = session[:referer_url] ||= root_path
  end

  # GET /pronunciations/1
  # GET /pronunciations/1.json
  def show
  end

  # GET /pronunciations/new
  def new
    @pronunciation = Pronunciation.new
  end

  # GET /pronunciations/1/edit
  def edit
  end

  # POST /pronunciations
  # POST /pronunciations.json
  def create
    @pronunciation = Pronunciation.new pronunciation_params
    
    respond_to do |format|
      if @pronunciation.save
        format.html { redirect_to @pronunciation, notice: 'Pronunciation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pronunciation }
      else
        format.html { render action: 'new' }
        format.json { render json: @pronunciation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pronunciations/1
  # PATCH/PUT /pronunciations/1.json
  def update
    case params[:phonemes]
    when nil
      @pronunciation.pronunciation_status = PronunciationStatus.approved
      @pronunciation.user = current_user
    when ''
      @pronunciation.phonemes = params[:phonemes]
      @pronunciation.pronunciation_status = PronunciationStatus.missing
    else
      @pronunciation.phonemes = params[:phonemes]
      @pronunciation.pronunciation_status = PronunciationStatus.needs_review
    end
    if @pronunciation.save
      render :json => @pronunciation.to_json(
        :only => [:dictionary_key, :phonemes],
        :include => {:user => {:only => :name}, :pronunciation_status => {:only => :name}}
      )
    else
      render json: @pronunciation.errors, status: :unprocessable_entity
    end
  end

  # DELETE /pronunciations/1
  # DELETE /pronunciations/1.json
  def destroy
    @pronunciation.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pronunciation
      @pronunciation = Pronunciation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pronunciation_params
      params[:pronunciation].permit(:dictionary_key, :phonemes)
    end
end

app/helpers/pronunciations_helper.rb
module PronunciationsHelper
  def per_page
    @per_page = request.params['per_page']
    if @per_page == nil
      @per_page = 30
    end
    @per_page.to_i
  end

  def sortable(title)
    @request_order = request.params['order']
    @order = @request_order == 'desc' ? 'asc' : 'desc'
    link_to title, params.merge(:order => @order, :page => 1), {:class => "sort-icon #{@order}"}
  end

  def clear_search
    attribute = request.params[:search]
    link_to "Clear Search", params.merge(:search => '', :page => 1), {:class => (attribute.nil? || attribute.empty? ? "link hide" : "link"), id: "clear_search"}
  end

  def clear_filter
    attribute = request.params[:filter]
    link_to "Clear Filter", params.merge(:filter => '', :page => 1), {:class => (attribute.nil? || attribute.empty? || attribute.to_i == -1 ? "link hide" : "link"), id: "clear_filter"}
  end

  def pronunciation_span(pronunciation)
    status_name = pronunciation.pronunciation_status.name
    class_name = status_name.gsub(/[ ]/,'-').downcase
    if status_name == 'Approved'
      content_tag(:span, '', :class =>"#{class_name} word-status" , :title => "Approved by #{pronunciation.user.name}")
    else
      content_tag(:span, '', :class =>"#{class_name} word-status" , :title => "#{status_name}")
    end
  end
end

app/views/pronunciations/_form.html.erb
<%= form_for(@pronunciation) do |f| %>
  <% if @pronunciation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pronunciation.errors.count, "error") %> prohibited this pronunciation from being saved:</h2>

      <ul>
      <% @pronunciation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pronunciations/_table.html.erb
<section class="table-containter">
  <header class="pure-g">
    <div class="pure-u-2-5">
      <input type="text" class="pure-input" name="search" value="<%= @search %>">
      <button id="search-btn" class="pure-button pure-button-small">Search</button>
      <%= clear_search %>
    </div>
    <div class="pure-u-1-5 align-center">
      <%= link_to "Audio Library", word_audio_status_index_path, :class => "pure-button pure-button-small" %>
    </div>
    <div class="pure-u-2-5 align-right">
      <label for="filter">Filter Status By</label>
      <%= select_tag 'filter', options_from_collection_for_select(PronunciationStatus.all, 'id', 'name', @filter), options ={:prompt => "None Selected"}%>
      <%= clear_filter %>
    </div>
  </header>
  <section class="pure-u" id="pronunciation_table">
    <table class="pure-table pure-table-horizontal pure-table-striped pure-table-1">
      <colgroup>
        <col style="width: 86px;">
        <col style="width: 250px;">
        <col style="width: 594px;">
      </colgroup>
      <thead>
        <tr>
          <th>Status</th>
          <th class="pronunciation-sort">
            <%= sortable "Word/Alternate Text" %>
          </th>
          <th>Pronunciation</th>
        </tr>
      </thead>
      <tbody>
        <% if @pronunciations.empty? %>
          <tr><td colspan="3">
            <p class="empty-info">No results to show with the current filter.</p>
          </td></tr>
        <% else %>
          <% @pronunciations.each do |pronunciation| %>
            <tr id="pronunciation_<%= pronunciation.id %>">
              <td><%= pronunciation_span(pronunciation) %></td>
              <td><span class="word"><%= pronunciation.dictionary_key %></td>
              <td><div class="desc"><%= pronunciation.phoneme %></div></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="pagination">
      <div class="dataTables_info">Total: <%= @pronunciations.total_entries %></div>
      <div class="dataTables_paginate paging_full_numbers">
        <%= will_paginate @pronunciations, {:renderer => "PaginationHelper::LinkRenderer", previous_label: '', next_label: '&nbsp;', container: false} %>
        <%= page_entries_info @pronunciations %>
      </div>
      <div class="dataTables_length">
        <%= hidden_field_tag "order", @request_order %>
        <%= hidden_field_tag "page", '1' %>
        <label>Item Per Page
          <%= select_tag "per_page", options_for_select([[10,10],[30,30],[50,50],[100,100],["Show All",-1]], per_page) %>
        </label>
      </div>
    </div>
  </section>
</section>

app/views/pronunciations/edit.html.erb
<h1>Editing pronunciation</h1>

<%= render 'form' %>

<%= link_to 'Show', @pronunciation %> |
<%= link_to 'Back', pronunciations_path %>

app/views/pronunciations/index.html.erb
<article class="content-container pure-u-1">
  <div class="content">
    <header>
      <h1>Word Audio and Pronunciations: Pronunciation Library</h1>
      <%= link_to "< Back", @referer_url, :class => "link", :title => "back" %>
    </header>
    <%= form_for(:pronunciation, method: :GET, html: { class: "pure-form" , id: "pronunciation_form"}) do |f| %>
      <%= render 'table' %>
    <% end %>
  </div>
</article>

app/views/pronunciations/index.js.erb
$('#pronunciation_form').html('<%= escape_javascript(render("table")) %>');
$('.word-status').qtip();

app/views/pronunciations/new.html.erb
<h1>New pronunciation</h1>

<%= render 'form' %>

<%= link_to 'Back', pronunciations_path %>

app/views/pronunciations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pronunciation_path(@pronunciation) %> |
<%= link_to 'Back', pronunciations_path %>