config/routes.rb
Cpt::Application.routes.draw do
  resources :word_audio_status, only: [:index, :show, :update, :edit]
  resources :glue_words, only: [:new]
  post 'glue_words/upload', to: 'glue_words#upload', as: 'glue_words_upload'

  resources :content_packs
  resources :pronunciations, only: [:index, :update]
  resources :audios, only: [:update]

  resources :content_packs do
    resources :topics, shallow: true
    resources :selections

    post 'topics/ordering/:id', to: 'topics#ordering', as: 'ordering_topics'
    post 'selections/ordering/:id', to: 'selections#ordering', as: 'ordering_selections'
    get 'selections/:id/move_copy', to: 'selections#move_copy', as: 'move_copy_new'
    post 'selections/:id/move', to: 'selections#move'
    post 'selections/:id/copy', to: 'selections#copy'
  end

  get 'auth/:provider', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#index', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => "content_packs#index"

end

app/models/word.rb
class Word < ActiveRecord::Base
  before_save {self.text = text.downcase }
  before_create :create_audio_associate
  
  belongs_to :word_audio_status
  
  validates :text, presence: true, length: { maximum: 255 }
  validates :alt_text, length: { maximum: 1024 }
  
  attr_accessor :audio
  
  private
    def create_audio_associate
      self.audio ||= Audio.new
      self.word_audio_status = WordAudioStatus.create_with(audio: self.audio)
                                          .find_or_create_by(spelling: text, audio_id: audio.id)
    end
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/_table.html.erb
<%= hidden_field_tag :keyword, @search_key_word %>
<table class="pure-table pure-table-horizontal pure-table-striped pure-table-1" id="audio_library_table">
  <colgroup>
    <col style="width: 86px;">
    <col style="width: 89px;">
    <col style="width: 250px;">
    <col style="width: 505px;">
  </colgroup>
  <thead>
    <tr>
      <th>Status</th>
      <th>Enable</th>
      <th>Word</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><span class="word-status approve"></span></td>
      <td></td>
      <td><span class="word">1500</td>
      <td></td>
    </tr>
    <tr>
      <td><span class="word-status need-review"></span></td>
      <td></td>
      <td><span class="word">1982</td>
      <td></td>
    </tr>
    <tr>
      <td><span class="word-status approve"></span></td>
      <td><input type="checkbox" name="do"></td>
      <td><span class="word">do</span></td>
      <td><span class="desc">do!1</span></td>
    </tr>
    <tr>
      <td><span class="word-status need-audio"></span></td>
      <td><input type="checkbox" name="do"></td>
      <td><span class="word red">do</span></td>
      <td><span class="desc">do!2</span></td>
    </tr>
    <%# @word_audio_statuses.each do |w| %>
    <!-- <tr>
      <td><%#= w.audio_status_id %></td>
      <td></td>
      <td><%#= w.spelling %></td>
      <td><%#= w.description %></td>
    </tr> -->
    <%# end %>
  </tbody>
</table>
<div class="pagination">
  <div class="dataTables_info">Total: 2</div>
  <div class="dataTables_paginate paging_full_numbers">
    <%= will_paginate(@word_audio_statuses, container: false, previous_label: "", next_label: "&nbsp;") %></a>
  </div>
  <div class="dataTables_length" id="words_table_length">
    <%= label_tag 'per_page' do %>Item Per Page
      <%= select_tag "per_page", options_for_select([[10,10],[30,30],[50,50],[100,100],["Show All",-1]],@per_page) %>
    <% end %>
  </div>
</div>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>


ruby plain

MVC

app/views/words/index.html.erb
<article class="content-container pure-u-1">
  <div class="content">
    <header>
      <h1>Word Audio and Pronunciations: Audio Library</h1>
      <%= link_to "< Back", @referer_url, :class => "link", :title => "back" %>
    </header>
    <section class="table-containter">
      <%= form_tag words_path, method: :get, id: "words_form", class: "pure-form" do %>
      <header class="pure-g">
        <div class="pure-u-2-5">
          <%= text_field_tag 'search_text', @search_key_word, placeholder: 'Enter search term...', class: "pure-input" %>
          <button type="submit" class="pure-button pure-button-small">Search</button>
          <%= link_to "Clear Search", "#", class: "link hide", id: "clear_search" %>
        </div>
        <div class="pure-u-1-5 align-center">
          <%= link_to "Pronunciation Library", pronunciations_path, :class => "pure-button pure-button-small" %>
        </div>
        <div class="pure-u-2-5 align-right">
          <label for="filter">Filter Status By</label>
          <select name="" id="filter">
            <option value="">None Selected</option>
            <option value="">Missing Audio</option>
            <option value="">No Audio Enabled</option>
            <option value="">Needs Review</option>
          </select>
          <%= link_to "Clear Filter", "#", :class => "link" %>
        </div>
      </header>
      <section class="pure-u" id="words_list">
        <%= render 'table' %>
      </section>
      <% end %>
    </section>
  </div>
</article>

app/views/words/index.js.erb
$('#words_list').html('<%= escape_javascript(render("table")) %>')
$('#clear_search').toggle(<%= !@search_key_word.blank? %>)

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>